runtime: java17
instance_class: F2
env: standard

env_variables:
  PORT: "8080"

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
